#!/usr/bin/env bash

# field 1 is the canline
# fields 2 is the address
# field 3 is the amount of bytes
# field 4 onward is the message

fname=""
t_fname=""
t_cmd_id=()
t_desc=()
t_data_type=()
packets_sent=0
packets_received=0
color="true"
oneline="false"

BLUE="\e[0;34m"
GREEN="\e[0;32m"

handle_translation() {
  #A translation file should be provided for easier readability
  local __TRAN_FILENAME="$1"
  while IFS='|' read -r cmd_id desc data_type; do
    t_cmd_id+=("${cmd_id:2:2}")
    t_desc+=("$desc")
    t_data_type+=("$data_type")
  done < <(tail -n +2 "$__TRAN_FILENAME")
}

print_help() {
  cat << 'EOF' 


  /$$$$$$   /$$$$$$   /$$$$$$   /$$$$$$$  /$$$$$$         /$$$$$$$  /$$$$$$  /$$$$$$$ 
 /$$__  $$ |____  $$ /$$__  $$ /$$_____/ /$$__  $$       /$$_____/ |____  $$| $$__  $$
| $$  \ $$  /$$$$$$$| $$  \__/|  $$$$$$ | $$$$$$$$      | $$        /$$$$$$$| $$  \ $$
| $$  | $$ /$$__  $$| $$       \____  $$| $$_____/      | $$       /$$__  $$| $$  | $$
| $$$$$$$/|  $$$$$$$| $$       /$$$$$$$/|  $$$$$$$      |  $$$$$$$|  $$$$$$$| $$  | $$
| $$____/  \_______/|__/      |_______/  \_______//$$$$$$\_______/ \_______/|__/  |__/
| $$                                             |______/                             
| $$                                                                                  
|__/                                                                                  


OVERVIEW: can debugger tool from candump logs
USAGE: parse_can -t <translation-file> -f <canlog-file>
OPTIONS:
  -t      Set the translation filename
  -f      Set the canlog filename
  -o      Set the output to spit everything out in one line
  -c      Removes color output
EOF
  

}

if [ $# = 0 ]; then
  print_help
  exit 0
fi

index_of() {
  local -n __TARGET_ARRAY=$1
  local __TARGET="$2"
  local __idx
  for __idx in "${!__TARGET_ARRAY[@]}"; do
    if [ "${__TARGET_ARRAY[$__idx]}" = "$__TARGET" ]; then
      return "$__idx"
    fi
  done
  return "255"
}

while getopts "ht:ocf:" opt; do
  case ${opt} in
  t) handle_translation "$OPTARG"; t_fname="l" ;;
  f) fname="$OPTARG" ;;
  h) print_help && exit 0 ;;
  c) color="false";;
  o) oneline="true" ;;
  *) echo "Invalid flag try again" ;;
  esac
done

if  [ -z "$t_fname" ]; then
  echo "Please provide a translation file"
  exit 1
fi



if  [ -z "$fname" ]; then
  echo "Please provide a file to be translated"
  exit 1
fi


readarray -t lines <"$fname"

for line in "${lines[@]}"; do
  CANLINE="$(echo "$line" | awk '{print $1}')"

  adr1="$(echo "$line" | awk '{print $2}')"

  ADDRESS="$adr1"

  b1="$(echo "$line" | awk '{print $3}' | tr -d '[]')"

  COMMAND="$(echo "$line" | awk '{print $4}')"

  MSG="$(echo "$line" | awk -v b="$b1" '{for (i = 4; i <= b+3; i++) print $i}' | tr '\n' ' ')"
  index_of t_cmd_id "$COMMAND"
  ind=$?
  if [ "$ind" = "255" ]; then
    echo "Invalid command ID"
    continue
  fi

  send_or_rcv=""
  if [ "${ADDRESS[$i]:0:1}" = "1" ]; then
    send_or_rcv="SEND"
  else
    send_or_rcv="RECV"
  fi
  d_pre_cli="${t_data_type[$ind]}"
  d_data_types=()
  d_descriptors=()
  while IFS= read -r entry; do
    d_data_types+=("$(echo "$entry" | awk 'BEGIN {FS=":"} {print $1}')")
    d_descriptors+=("$(echo "$entry" | awk 'BEGIN {FS=":"} {print $2}')")
  done < <(echo "$d_pre_cli" | awk 'BEGIN {FS=","} {for (i=1; i<=NF; i++) print $i}')

  if [ "${d_data_types[0]}" = "None" ]; then
    echo "$send_or_rcv $ADDRESS: ${t_desc[$ind]}: No data"
  else
    raw="$(echo "$MSG" | ./hex_to_int "$BYTES" "${d_data_types[@]}")"
    read -ra values <<<"$raw  "
    output_string=""
    output_string+="$send_or_rcv $ADDRESS"
    if [ "$color" = "true" ]; then
      output_string+="$BLUE"
    fi
    output_string+=" ${t_desc[$ind]}:"
    if [ "$color" = "true" ]; then
      output_string+="\e[0m"
    fi
    output_string+=" \n"


    v_idx=0
    for d_idx in "${!d_data_types[@]}"; do
      if [ "${d_data_types[$d_idx]}" = "NULL" ]; then
        continue
      fi
      if [ "$color" = "true" ]; then
        output_string+="$GREEN"
      fi
      output_string+="  ${d_descriptors[$d_idx]}: " 
      if [ "$color" = "true" ]; then
        output_string+="\e[0m"
      fi

      output_string+="${values[$v_idx]}"
      output_string+=" \n"
      v_idx=$((v_idx + 1))
    done
    
    if [ "$oneline" = "true" ]; then
      output_string="${output_string//\\n/}"
    fi


    echo -e "$output_string"
  fi


done

